Campaign:
    # Can be auto or the name of a plane set
    PlaneSet: auto
    # Whether to use the textual mission file (slow but better compatibility with new versions of the game)
    # Otherwise the binary file is used (fast, but new versions of the game often change that format)
    UseTextMissionFile: false
    # Seed for the random generator; affects weather
    Seed: 42
    # Max deviation of the weather with respect of standard weather for start date
    WeatherDayMaxOffset: 7
    # Max number of fires (on destroyed storage/factories)
    MaxFires: 20
    # Max number of spotted building icons (per type and coalition)
    MaxBuildingIcons: 10
    # Max number of convoys in mission (per side)
    MaxConvoys: 8
    # Max number of attacker planes (per side)
    MaxAttackers: 3
    # Max number of patrols (per side, two planes per patrol)
    MaxPatrols: 2
    # Max number of captured planes available for spawning (per airfield)
    MaxCapturedPlanes: 0
    # Base name of generated mission file
    # Each round two files are generated. They are named after the parameter below, with _1 and _2 appended.
    # You should set your sds file to use a mission rotation with two missions, using these names.
    # This avoids issues with locked mission files that typically arise when replacing the old mission file while DServer is running and sending files to players currently connecting.
    # These files are copied to <ServerDataDir>/Multiplayer/Dogfight
    MissionName: DynCampaign
    # Length of mission, in minutes
    MissionLength: 180
    # If early morning and late evening night time should be included in missions. Searchlights give a nice ambience, but they heavily affects gameplay, as AA is inactive after searchlights are destroyed.
    LongWorkDay: false
    # Interval between group of vehicles in a column (for columns larger than 15 tanks)
    ColumnSplitInterval: 60
    # Max number of convoys active simultaneously (per side)
    MaxSimultaneousConvoys: 2
    # Max number of ferry flights active simultaneously (per side)
    MaxSimultaneousFerryFlights: 2
    # Max number of vehicles in a battle (per side)
    MaxVehiclesInBattle: 15
    # Number of in-game tank kills per battle resolution kills
    BattleKillRatio: 5
    # Ratio of max in-game tank kills (by players) in battles
    MaxBattleKillsRatioByPlayers: 1.0
    # Ratio of max in-game tank kills (by AI) in battles
    MaxBattleKillsRatioByAI: 0.25
    # Max static planes per airfield
    MaxStaticPlanes: 6
    # Control whether player-driven tank spawns should be included in battles
    EnablePlayerTanks: true
    # Where the textual generated mission file is written; this also the place where the campaign state is kept
    OutputDir: C:\Campaign\Data
    # IL2 data dir
    ServerDataDir: C:\il2\data
    # If true, enable chatlog commands: Players can type in commands in the chat to interact with the campaign software.
    # Disabled by default, as this requires the frequent sent of cutchatlog commands to DServer, which appears to make it crash.
    ChatLogCommandsEnabled: false
    # IL2 bin dir
    ServerBinDir: C:\il2\bin
    # SDS file, relative to data dir
    ServerSdsFile: sds\campaign.sds
    # Where this file resides
    InstallPath: C:\Campaign\Bin
    # Whether to purge old mission logs
    PurgeLogs: true
    # Max think time for column movement planning
    ThinkTime: 60
    # Total production of all factories in an average region. Used to compute production factor to adjust production per factory building on the map.
    DesiredProduction: 300.0
    # Amount of production (resource units per hour) for planes. 500.0f gives one i16 or bf109e7 per hour.
    PlaneProduction: 2000.0
    # Fixed part of the mission briefing
    Briefing: |
        This mission is part of a dynamic campaign where the events from one mission affect the following missions.
        
        Objectives: Truck convoys, tank columns, field camps (look for dugouts), factories, parked planes, anti-air cannons.
        
        Each region has a 'life bar' indicating the storage health (colored bar) and current supply level (color of the bar).
        If the bar is red, the region is poorly defended. If it's green, it's fully defended.
        If the bar is short, it means storage is damaged. The shorter the bar, the mode damage.
        
        Some regions have numbers beside their name: these represent the number of tanks in that region at the start of the mission.
        
        Planes can be transferred from one airfield to another, but the result will only be visible in the next mission.

    # If non-empty, webhook URL of a discord channel where comments extracted from the ongoing mission log entries will be posted.
    WebHook: ""
    # Max number of friendly fire incidents. Ban occurs when that number is reached
    MaxFriendlyFireEvents: 2
    # Duration of ban for friendly fire
    FriendlyFireBanDuration: 1
    # Maximum "noob score". When reached, player is banned for NoobBanDuration. Self-inflicted damage after take-off gives 1.0 pt, before take-off 2.0 pts. Friendly fire gives 1.0 pt
    MaxNoobScore: 3.0
    # Ban duration for excessively clumsy players, in hours. 0 will still give the in-game ban of 15min.
    NoobBanDuration: 1