Campaign:
    # Can be Stalingrad, Moscow, VelikieLuki, EarlyAccess
    PlaneSet: Stalingrad
    # Name of file describing the scenario
    StrategyFile: StalingradSummer.Mission
    # Seed for the random generator; affects weather
    Seed: 42
    # Max deviation of the weather with respect of standard weather for start date
    WeatherDayMaxOffset: 7
    # Max number of fires (on destroyed storage/factories)
    MaxFires: 20
    # Max number of convoys in mission (per side)
    MaxConvoys: 8
    # Max number of attacker planes (per side)
    MaxAttackers: 3
    # Max number of patrolling fighters (per side)
    MaxPatrols: 4
    # Max number of captured planes available for spawning (per airfield)
    MaxCapturedPlanes: 0
    # Base name of generated mission file
    MissionName: DynCampaign
    # Length of mission, in minutes
    MissionLength: 180
    # Interval between group of vehicles in a column (for columns larger than 15 tanks)
    ColumnSplitInterval: 60
    # Max number of convoys active simultaneously (per side)
    MaxSimultaneousConvoys: 2
    # Max number of ferry flights active simultaneously (per side)
    MaxSimultaneousFerryFlights: 2
    # Max number of vehicles in a battle (per side)
    MaxVehiclesInBattle: 15
    # Number of in-game tank kills per battle resolution kills
    BattleKillRatio: 5
    # Ratio of max in-game tank kills (by players) in battles
    MaxBattleKillsRatioByPlayers: 1.0
    # Ratio of max in-game tank kills (by AI) in battles
    MaxBattleKillsRatioByAI: 0.25
    # Where the textual generated mission file is written; this also the place where the campaign state is kept
    OutputDir: C:\Campaign\Data
    # IL2 data dir
    ServerDataDir: C:\il2\data
    # IL2 bin dir
    ServerBinDir: C:\il2\bin
    # SDS file, relative to data dir
    ServerSdsFile: sds\campaign.sds
    # Where this file resides
    InstallPath: C:\Campaign\Bin
    # Max think time for column movement planning
    ThinkTime: 60
    # Total production of all factories in an average region. Used to compute production factor to adjust production per factory building on the map.
    DesiredProduction: 300.0
    # Amount of production (resource units per hour) for planes. 500.0f gives one i16 or bf109e7 per hour.
    PlaneProduction: 2000.0
    # Fixed part of the mission briefing
    Briefing: |
        This mission is part of a dynamic campaign where the events from one mission affect the following missions.
        
        Objectives: Truck convoys, tank columns, field camps (look for dugouts), factories, parked planes, anti-air cannons.
        
        Each region has a 'life bar' indicating the storage health (colored bar) and current supply level (color of the bar).
        If the bar is red, the region is poorly defended. If it's green, it's fully defended.
        If the bar is short, it means storage is damaged. The shorter the bar, the mode damage.
        
        Some regions have numbers beside their name: these represent the number of tanks in that region at the start of the mission.
        
        Planes can be transferred from one airfield to another, but the result will only be visible in the next mission.

    # If non-empty, webhook URL of a discord channel where comments extracted from the ongoing mission log entries will be posted.
    WebHook: ""
    # Max number of friendly fire incidents. Ban occurs when that number is reached
    MaxFriendlyFireEvents: 2
    # Duration of ban for friendly fire
    FriendlyFireBanDuration: 1
    # Maximum "noob score". When reached, player is banned for NoobBanDuration. Self-inflicted damage after take-off gives 1.0 pt, before take-off 2.0 pts. Friendly fire gives 1.0 pt
    MaxNoobScore: 3.0
    # Ban duration for excessively clumsy players, in hours. 0 will still give the in-game ban of 15min.
    NoobBanDuration: 1