Multiplayer Dynamic Campaign for IL-2: Great Battles by Coconut
===============================================================
Johann "coconut" Deneux <johann.deneux@gmail.com>

== Preamble

This dynamic campaign system is Coconut's second attempt. This new attempt builds upon it, retaining the following concepts:
- A large play area divided in regions
- Persistent damage
- Logistics affected by infrastructure, such as bridges and factories
- Campaign status update between missions
- Plane availability affected by losses and transfers

The biggest change with the previous version is the campaign simulation mechanisms.
It used to be the case that status change was the result of an action that took place in the game: The transfer of a plane, the destruction of one side in a battle, the travelling of a truck...
The problem with this approach is that the full logistics of a war required a number of actors (planes, tanks, trucks...) that was too big for a mission.
Because of this, every individual in-game actor represented a sometimes excessively large asset, and its destruction could lead to unrealistically large losses.
Such destruction was not even always the result of players' actions. Entire armies were lost to a misplaced very robust fence encroaching on a road...

== Principles

There are two sides, Allies and Axis, which each control _regions_. A region is a fixed geographical area, controlled by at most one side.
A region has _infrastructure_ consisting of all buildings except civilian houses. A region can also be home to a number of _airfields_, which have their own infrastructure (typically hangars, fuel tanks...).

Regions are _connected_ by _roads_ and _railways_, which can cross rivers with _bridges_. Roads and railways have a _transport capacity_. Bridges can be destroyed, resulting in a loss of capacity in the transportation network.

At any given date, a region can be occupied by _ground forces_, characterized by a number. Both sides can have forces in a region simultaneously.
When a region has forces from one side only, that region falls under the control of that side, and will remain so until the other side enters the region with their forces, while the until-then controlling side has no forces there.
Regions can also be captured as the result of a _battle_, when the forces belonging to the side controlling the region are defeated or surrender.

Ground forces are simply characterized by numbers, the exact breakdown by vehicle type is not tracked.

Airfields host _planes_, which are accounted for: A plane can be added at an airfield by landing there, and removed by taking off. Planes can be (partially) _damaged_.
Planes are counted as "volumes", meaning that two planes damaged to 50% count as a single healthy plane.

Both planes and ground forces are replenished at regular intervals. They materialize in so called _entry regions_, of which each side has at least one.

The effectiveness of ground forces and the speed of _repairs_ to infrastructure is affected by connectivity from the region (where the forces or assets are located) to the entry region(s).
Forces in an isolated region have reduced efficiency during battles.

Planes and ground forces can be destroyed during gameplay, but also between missions as part as _simulation_. The simulation covers battles between ground forces, transfers of ground forces, _air missions_.
Air missions consist of attacks and patrols. Air encounters are simulated, and the results are affected by respective number of participants and their experience.

The experience of an air force is affected by its _home airfield_ and the availability of experienced _pilots_. Pilots are _controlled_ by players, and their achievements, health and location is tracked.

Whenever a player takes off from a new airfield, they take control of a fresh pilot. When they land back at an airfield, or at least near an airfield, that airfield becomes the new location of that pilot.

Pilots can be injured, in which case they become unavailable for a period of time that depends on the injury. New pilots are introduced as needed.

Pilots gain experience by flying missions in which "interesting things happen", typically they inflict damage to the enemy, or receive damage from the enemy. Alternatively, long flights count also as granting experience.

The number of pilots and their experience in a region affect positively the simulation of all missions that originate from that region.