# Region numbers
#    | Stalingrad = 0
#    | VelikieLuki = 1
#    | Moscow = 2
#    | Kuban = 3

# Static plane models, see Vehicles.mission
#     | Axis:
#          0: GermanStaBf109
#             GermanStaBf109Net
#             GermanStaBf109Open
#             GermanStaBf109e7
#             GermanStaBf109e7Net
#          5: GermanStaBf109e7Open
#             GermanStaAttacker
#             GermanStaJu87
#             GermanStaJu87Net
#             GermanStaBomber
#         10: GermanStaHe111h6
#             GermanStaTransport
#     | Allies:
#          0: RussianStaI16
#             RussianStaI16Net
#             RussianStaLagg3
#             RussianStaLagg3Net
#             RussianStaLagg3W1
#          5: RussianStaLagg3W2
#             RussianStaMig3
#             RussianStaMig3Net
#             RussianStaYak1
#             RussianStaYak1Net
#         10: RussianStaYak1Open
#             RussianStaAttacker
#             RussianStaBomber

PlaneSet:
    Name: FlyingCircus1
    Regions: [0, 1, 2, 3, 4, 5]
    StartDate: "1-Jan-1914"
    Planes:
        - Model: Fokker Dr.I
          Static: 1
        - Model: Pfalz D.IIIa
          Static: 4
        - Model: Sopwith Camel
          Static: 1
        - Model: Spad 13.C1
          Static: 3
