Campaign:
    # Can be auto or the name of a plane set
    PlaneSet: auto
    # List of campaign scenarios to run in sequence. If empty, automatic start of campaigns is Disabled.
    PlayList: [MoscowAutumn2, MoscowWinter, StalingradSummer, StalingradAutumn, KubanSpring, KubanAutumn]
    # Whether to use the textual mission file (slow but better compatibility with new versions of the game)
    # Otherwise the binary file is used (fast, but new versions of the game often change that format)
    UseTextMissionFile: false
    # Seed for the random generator; affects weather
    Seed: 42
    # Max deviation of the weather with respect of standard weather for start date
    WeatherDayMaxOffset: 7
    # Max number of AA cannons over the entire map
    MaxAACannons: 200
    # Max number of fires (on destroyed storage/factories)
    MaxFires: 20
    # Max number of spotted building icons (per type and coalition)
    MaxBuildingIcons: 10
    # Max number of convoys in mission (per side)
    MaxConvoys: 8
    # Max number of attacker planes (per side)
    MaxAttackers: 3
    # Max number of patrols (per side, two planes per patrol)
    MaxPatrols: 2
    # Max number of captured planes available for spawning (per airfield)
    MaxCapturedPlanes: 0
    # Base name of generated mission file
    # Each round two files are generated. They are named after the parameter below, with _1 and _2 appended.
    # You should set your sds file to use a mission rotation with two missions, using these names.
    # This avoids issues with locked mission files that typically arise when replacing the old mission file while DServer is running and sending files to players currently connecting.
    # These files are copied to <ServerDataDir>/Multiplayer/Dogfight
    MissionName: DynCampaign
    # Length of mission, in minutes
    MissionLength: 180
    # If early morning and late evening night time should be included in missions. Searchlights give a nice ambience, but they heavily affects gameplay, as AA is inactive after searchlights are destroyed.
    LongWorkDay: false
    # Interval between group of vehicles in a column (for columns larger than 15 tanks)
    ColumnSplitInterval: 60
    # Max number of convoys active simultaneously (per side)
    MaxSimultaneousConvoys: 2
    # Max number of ferry flights active simultaneously (per side)
    MaxSimultaneousFerryFlights: 2
    # Maximum number of tanks in each park
    MaxTanksInParks: 15
    # Max number of vehicles in a battle (per side)
    MaxVehiclesInBattle: 15
    # Number of in-game tank kills per battle resolution kills
    BattleKillRatio: 5
    # Ratio of max in-game tank kills (by players) in battles
    MaxBattleKillsRatioByPlayers: 1.0
    # Ratio of max in-game tank kills (by AI) in battles
    MaxBattleKillsRatioByAI: 0.25
    # Max static planes per airfield
    MaxStaticPlanes: 16
    # Whether spawn restrictions are in place
    SpawnRestrictions: true
    # Every time a player shoots down 3 planes, they get an additional fresh luxury spawn. This bonus is reset when the pilot is killed or captured. (per player)
    MaxLuxuryBonusSpawns: 2
    # Max number of "best plane" spawns at rear airfield (per player)
    FreshLuxurySpawns: 2
    # Max number of fighter spawns at rear airfield (per player)
    FreshFighterSpawns: 5
    # Max number of attacker spawns at rear airfield (per player)
    FreshAttackerSpawns: 5
    # Max number of bomber spawns at rear airfield (per player)
    FreshBomberSpawns: 3
    # Max number of transport spawns at rear airfield (per player)
    FreshTransportSpawns: 3
    # Number of new fresh fighter spawns each new mission (per player)
    FreshFighterRefill: 1.5
    # Number of new fresh attacker spawns each new mission (per player)
    FreshAttackerRefill: 1.5
    # Number of new fresh bomber spawns each new mission (per player)
    FreshBomberRefill: 1.0
    # Number of new fresh transport spawns each new mission (per player)
    FreshTransportRefill: 1.0
    # Max amount of cash a player can hold
    MaxCash: 10000
    # Initial amount of cash for each player
    InitialCash: 0
    # Control whether player-driven tank spawns should be included in battles
    EnablePlayerTanks: true
    # Where the textual generated mission file is written; this also the place where the campaign state is kept
    OutputDir: C:\Campaign\Data
    # IL2 data dir
    ServerDataDir: C:\il2\data
    # If true, enable chatlog commands: Players can type in commands in the chat to interact with the campaign software.
    # Disabled by default, as this requires the frequent sent of cutchatlog commands to DServer, which appears to make it crash.
    ChatLogCommandsEnabled: false
    # IL2 bin dir
    ServerBinDir: C:\il2\bin
    # SDS file, relative to data dir
    ServerSdsFile: sds\campaign.sds
    # Where this file resides
    InstallPath: C:\Campaign\Bin
    # Whether to purge old mission logs
    PurgeLogs: true
    # Max think time for column movement planning
    ThinkTime: 60
    # Total production of all factories in an average region. Used to compute production factor to adjust production per factory building on the map.
    DesiredProduction: 150.0
    # Initial number of planes at rear airfield
    RearAirfieldPlanes: 5000
    # Fixed part of the mission briefing
    Briefing: |
        This mission is part of a dynamic campaign where the events from one mission affect the following missions.
        
        Objectives: Truck convoys, tank columns, field camps (look for dugouts), factories, parked planes, anti-air cannons.
        
        Each region has a 'life bar' indicating the storage health (colored bar) and current supply level (color of the bar).
        If the bar is red, the region is poorly defended. If it's green, it's fully defended.
        If the bar is short, it means storage is damaged. The shorter the bar, the mode damage.
        
        Some regions have numbers beside their name: these represent the number of tanks in that region at the start of the mission.
        
        Planes can be transferred from one airfield to another, but the result will only be visible in the next mission.

    # If non-empty, webhook URL of a discord channel where comments extracted from the ongoing mission log entries will be posted.
    WebHook: ""
    # User ID to use in "hey @user something went wrong with the server"
    DiscordUserId: ""
    # Max number of friendly fire incidents. Ban occurs when that number is exceeded
    MaxFriendlyFireEvents: 2
    # Duration of ban for friendly fire
    FriendlyFireBanDuration: 1
    # Maximum "noob score". When reached, player is banned for NoobBanDuration. Self-inflicted damage after take-off gives 1.0 pt, before take-off 2.0 pts. Friendly fire gives 1.0 pt
    MaxNoobScore: 3.0
    # Ban duration for excessively clumsy players, in hours. 0 will still give the in-game ban of 15min.
    NoobBanDuration: 1