// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#r "../../DataProvider/bin/Debug/DataProvider.dll"
#r "System.Core.dll"
#r "System.dll"
#r "System.Numerics.dll"
#r "../../Blocks/packages/System.Numerics.Vectors.4.3.0/lib/portable-net45+win8+wp8+wpa81/System.Numerics.Vectors.dll"
#r "../../../../../../Program Files (x86)/Reference Assemblies/Microsoft/FSharp/.NETFramework/v4.0/4.3.0.0/Type Providers/FSharp.Data.TypeProviders.dll"
#r "System.Data.dll"
#r "System.Data.Linq.dll"
#r "../../Blocks/packages/FsPickler.3.2.0/lib/net45/FsPickler.dll"
#r "../../Blocks/packages/FsPickler.Json.3.2.0/lib/net45/FsPickler.Json.dll"
#r "System.Runtime.Serialization.dll"
#r "System.Xml.dll"
#r "../../Blocks/packages/Newtonsoft.Json.9.0.1/lib/net45/Newtonsoft.Json.dll"
#r "../../../plog/ploggy/bin/Debug/ploggy.dll"
#r "../../Blocks/packages/NLog.4.4.4/lib/net45/NLog.dll"