// Warning: generated file; your changes could be lost when a new file is generated.
#I __SOURCE_DIRECTORY__
#load "load-references-debug.fsx"
#load "../AssemblyInfo.fs"
      "../Util.fs"
      "../WorldDescription.fs"
      "../WorldState.fs"
      "../Weather.fs"
      "../Orders.fs"
      "../AutoOrder.fs"
      "../MapGraphics.fs"
      "../MissionGeneration.fs"
      "../ResultExtraction.fs"
      "../NewWorldState.fs"
      "../Run.fs"
